FROM ghcr.io/coollabsio/minio:RELEASE.2025-10-15T17-29-55Z

COPY --chmod=0555 scripts/provision-minio.sh /opt/schoolbase/provision-minio.sh
COPY --chmod=0555 scripts/prepare-database-import.sh /opt/schoolbase/prepare-database-import.sh
