FROM ghcr.io/coollabsio/minio:RELEASE.2025-10-15T17-29-55Z AS minio-client

FROM postgres:16.15-alpine

COPY --from=minio-client /usr/bin/mc /usr/local/bin/mc
COPY --chmod=0555 scripts/provision-postgres.sh /opt/schoolbase/provision-postgres.sh
COPY --chmod=0555 scripts/restore-postgres.sh /opt/schoolbase/restore-postgres.sh
